/* Mi casa, mi ritmo · Trucos y soluciones */
(function(){'use strict';
const T=[
['🍳','Cocina','Grasa diaria en cocina','Ecojin · mezcla habitual','Para encimera, frentes y grasa diaria: usa la mezcla habitual de Ecojin que tengas preparada. Pulveriza poca cantidad, pasa la bayeta y retira bien.'],
['🍲','Cocina','Cazuela quemada','Ecojin','Con la cazuela sin agua, pon aproximadamente ½ tapón de Ecojin y pon la cazuela a calentar. El calor es parte del truco: en frío no funciona igual. Después retira del fuego, trabaja la suciedad y lava y aclara muy bien. Comprueba antes que el material de la cazuela admite este uso.'],
['🍳','Cocina','Sartén con grasa pegada','Ecojin','Calienta primero la sartén. Retírala del fuego, aplica un par de flis-flas de Ecojin y frota la suciedad. Después lava y aclara muy bien antes de volver a cocinar. Comprueba antes que el material de la sartén admite este uso.'],
['🔥','Cocina','Horno con grasa','Ecojin','Enciende el horno y déjalo calentar unos 5 minutos. Después apágalo y procede a limpiarlo con Ecojin mientras conserva el calor. Retira bien toda la grasa y los restos de producto antes de volver a usar el horno.'],
['🧺','Ropa','Manchas en ropa','Ecojin','En manchas compatibles con el tejido, aplica una pequeña cantidad sobre la mancha, deja actuar poco tiempo y lava normalmente. Prueba antes en una zona poco visible y no dejes secar el producto sobre la prenda.'],
['🧹','Suelos','Limpieza habitual del suelo','Limpiasuelos Laboncler','Para el suelo diario, usa el limpiasuelos habitual de Laboncler con la dosis indicada en su envase.'],
['🚰','Desagües','Mantenimiento preventivo','Prometeo','Prometeo es para mantenimiento y prevención del desagüe, antes de que exista un atasco real. Sigue su dosis y tiempo de actuación y no lo mezcles con otros productos.'],
['⚠️','Desagües','Atasco real','Pandora','Pandora es para cuando ya existe un atasco, no para mantenimiento rutinario. Sigue estrictamente su etiqueta, ventila, protege piel y ojos y nunca lo mezcles con lejía, ácidos ni otros desatascadores.'],
['🧪','Limpieza fuerte','Suciedad difícil cuando corresponda','Poseidón','Poseidón es un producto fuerte: úsalo solo en superficies y situaciones para las que esté indicado y respetando la etiqueta. 💦 ACLARAR CON ABUNDANTE AGUAAAA. No mezclar con otros productos.'],
['🚿','Baño','Mampara con cal','Antical compatible','Usa un antical apto para el material de la mampara, deja actuar únicamente el tiempo indicado y aclara bien. Nunca mezcles anticales o ácidos con lejía.'],
['🧹','General','No sé por dónde empezar','Mi casa, mi ritmo','No hace falta decidir qué limpiar. Entra en Hoy: la aplicación ya ha preparado lo que toca. Revisa la lista, comprueba quién hace cada cosa si sois varias personas y marca las tareas al terminarlas.']
];
function installBox(){let sec=document.getElementById('casa');if(!sec||document.getElementById('trucosBox'))return;let box=document.createElement('div');box.id='trucosBox';box.className='card';box.innerHTML='<div class="row"><div><h2>💡 Trucos y soluciones</h2><div class="muted">Busca el problema y te digo qué usar y cómo.</div></div><button class="mini" id="trucosOpen">Abrir</button></div><div id="trucosPanel" class="hidden" style="margin-top:12px"><input id="trucosSearch" class="field" placeholder="Buscar: horno, sartén, cazuela, atasco…"><div class="chips" id="trucosCats" style="margin-top:8px"></div><div id="trucosList"></div></div>';let hero=sec.querySelector('.hero');if(hero)hero.after(box);else sec.prepend(box);box.querySelector('#trucosOpen').onclick=function(){let p=box.querySelector('#trucosPanel');p.classList.toggle('hidden');this.textContent=p.classList.contains('hidden')?'Abrir':'Cerrar';if(!p.classList.contains('hidden'))draw()};box.querySelector('#trucosSearch').oninput=draw;drawCats()}
let cat='Todos';function drawCats(){let el=document.getElementById('trucosCats');if(!el)return;let cats=['Todos',...new Set(T.map(x=>x[1]))];el.innerHTML=cats.map(c=>'<button class="chip '+(cat===c?'on':'')+'" data-cat="'+c+'">'+c+'</button>').join('');el.querySelectorAll('[data-cat]').forEach(b=>b.onclick=function(){cat=this.dataset.cat;drawCats();draw()})}function draw(){let q=(document.getElementById('trucosSearch')?.value||'').trim().toLowerCase(),el=document.getElementById('trucosList');if(!el)return;let a=T.filter(x=>(cat==='Todos'||x[1]===cat)&&(!q||(x[2]+' '+x[3]+' '+x[4]+' '+x[1]).toLowerCase().includes(q)));el.innerHTML=a.length?a.map(x=>'<details class="task"><summary><b>'+x[0]+' '+x[2]+'</b><div class="meta">'+x[1]+' · <b>'+x[3]+'</b></div></summary><div class="softbox" style="margin-top:9px"><b>Qué usar: '+x[3]+'</b><div style="margin-top:6px">'+x[4]+'</div></div></details>').join(''):'<div class="empty">Todavía no tengo ese caso. Lo añadiremos sin inventarnos el remedio 😅.</div>'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installBox);else installBox();})();