/* Mi casa, mi ritmo · Trucos y soluciones */
(function(){'use strict';
const T=[
['🍳','Cocina','Grasa en encimera o muebles','Usa tu limpiador desengrasante habitual siguiendo su dosis. En grasa acumulada, deja actuar solo el tiempo indicado y retira bien.'],
['🍳','Cocina','Cazuela quemada','Empieza por agua caliente y limpieza suave. Si usas un producto concentrado, respeta siempre su dosis y el material de la cazuela.'],
['🔥','Cocina','Horno con grasa','Retira restos sueltos primero. Aplica el producto adecuado con el horno frío o templado según indique su etiqueta y aclara/retira completamente antes de volver a usarlo.'],
['🧺','Ropa','Mancha en una prenda','Actúa cuanto antes. Prueba primero en una zona poco visible y evita calor hasta comprobar que la mancha ha desaparecido.'],
['🚿','Baño','Mampara con cal','Empieza por un producto antical apto para la mampara. No mezcles productos y aclara bien después.'],
['🚽','Baño','WC y baño','Usa un producto específico para la superficie. Nunca mezcles lejía con ácidos, vinagre, amoniaco u otros limpiadores.'],
['🚰','Desagües','Mantenimiento preventivo','Para mantenimiento, usa únicamente un producto indicado para prevención y sigue exactamente su etiqueta. No combines desatascadores ni otros químicos.'],
['⚠️','Desagües','Atasco real','Si el atasco es importante, prioriza medios mecánicos o un profesional. Si utilizas un desatascador químico, sigue la etiqueta, ventila, protege piel y ojos y nunca mezcles productos.'],
['🧹','General','No sé por dónde empezar','Haz primero lo que cambia la sensación de la casa: camas, recogida visible, fregadero/encimera y baño. Después deja que Hoy decida el resto.']
];
function installBox(){let sec=document.getElementById('casa');if(!sec||document.getElementById('trucosBox'))return;let box=document.createElement('div');box.id='trucosBox';box.className='card';box.innerHTML='<div class="row"><div><h2>💡 Trucos y soluciones</h2><div class="muted">Para cuando aparece ese “¿y esto cómo lo limpio?”</div></div><button class="mini" id="trucosOpen">Abrir</button></div><div id="trucosPanel" class="hidden" style="margin-top:12px"><input id="trucosSearch" class="field" placeholder="Buscar: horno, cal, mancha, desagüe…"><div class="chips" id="trucosCats" style="margin-top:8px"></div><div id="trucosList"></div></div>';let hero=sec.querySelector('.hero');if(hero)hero.after(box);else sec.prepend(box);box.querySelector('#trucosOpen').onclick=function(){let p=box.querySelector('#trucosPanel');p.classList.toggle('hidden');this.textContent=p.classList.contains('hidden')?'Abrir':'Cerrar';if(!p.classList.contains('hidden'))draw()};box.querySelector('#trucosSearch').oninput=draw;drawCats()}
let cat='Todos';function drawCats(){let el=document.getElementById('trucosCats');if(!el)return;let cats=['Todos',...new Set(T.map(x=>x[1]))];el.innerHTML=cats.map(c=>'<button class="chip '+(cat===c?'on':'')+'" data-cat="'+c+'">'+c+'</button>').join('');el.querySelectorAll('[data-cat]').forEach(b=>b.onclick=function(){cat=this.dataset.cat;drawCats();draw()})}function draw(){let q=(document.getElementById('trucosSearch')?.value||'').trim().toLowerCase(),el=document.getElementById('trucosList');if(!el)return;let a=T.filter(x=>(cat==='Todos'||x[1]===cat)&&(!q||(x[2]+' '+x[3]+' '+x[1]).toLowerCase().includes(q)));el.innerHTML=a.length?a.map(x=>'<details class="task"><summary><b>'+x[0]+' '+x[2]+'</b><div class="meta">'+x[1]+'</div></summary><div class="softbox" style="margin-top:9px">'+x[3]+'</div></details>').join(''):'<div class="empty">No encuentro ese truco todavía.</div>'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installBox);else installBox();})();