/* Mi casa, mi ritmo · mejoras de uso real septiembre 2026 */
(function(){'use strict';
const VERSION='2026-09-17-dishwasher-flow-v5';
const rawCfg=typeof cfg==='function'?cfg:null;
function rawHome(){try{return rawCfg?(rawCfg()||{}):{}}catch(e){return{}}}
function todayWorkMinutes(h){let w=h.workSchedule||{},d=String(new Date().getDay());return w.type==='work'?Math.max(0,Number((w.minutesByDay||{})[d])||0):null}
if(rawCfg&&!rawCfg.__mcbWork){window.cfg=function(){let h=rawHome(),m=todayWorkMinutes(h);if(m!==null){h=JSON.parse(JSON.stringify(h));h.organization=h.organization||{};h.organization.minutes=m;h.organization.days=Object.keys((h.workSchedule&&h.workSchedule.minutesByDay)||{}).filter(k=>Number(h.workSchedule.minutesByDay[k])>0).map(Number)}return h};window.cfg.__mcbWork=true}
function c(){try{return typeof cfg==='function'?(cfg()||{}):{}}catch(e){return{}}}
function todayName(){return new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).replace(/^./,x=>x.toUpperCase())}
function addStyles(){if(document.getElementById('mcbSeptStyles'))return;let s=document.createElement('style');s.id='mcbSeptStyles';s.textContent='.chips{display:flex!important;flex-wrap:wrap!important;overflow:visible!important}.chip{white-space:normal!important;text-align:center}.mcb-day-title{margin:0 0 12px;padding:12px 14px;background:#e8eee2;border-radius:14px;font-weight:900;font-size:18px;color:#58704f}.mcb-appliance-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.mcb-transfer{width:100%;min-height:80px;margin-top:8px;padding:10px;border:1px solid #e8e1d7;border-radius:12px}.mcb-schedule-row{display:grid;grid-template-columns:95px 1fr;gap:9px;align-items:center;margin:7px 0}.mcb-schedule-row select{width:100%;padding:9px;border:1px solid #e8e1d7;border-radius:11px;background:#fff}';document.head.appendChild(s)}
function labelTask(t){if(!t)return t;let room={dorm:'dormitorio',salon:'salón',entrada:'entrada',cocina:'cocina',bano:'baño'}[t.room];if(room&&['Polvo','Recogida','Suelo','Suelo · mopa/fregona','Aspirar/barrer','Ventilar'].includes(t.text))return Object.assign({},t,{text:t.text+' · '+room});return t}
function wrapTaskHTML(){if(typeof taskHTML!=='function'||taskHTML.__mcbSept)return;let old=taskHTML;window.taskHTML=function(t){return old(labelTask(t))};window.taskHTML.__mcbSept=true}
function ironingTask(){let x=c().laundry||{},v=String(x.ironing||'').toLowerCase();if(!v||v==='no')return null;let min=Math.max(15,Number(state.ironingMinutes)||0);if(!min)min=v.includes('bastante')?180:60;return{id:'mcb_ironing',area:'colada',text:'Planchar ropa',min:min,priority:4,room:'colada'} }
function dishState(){if(!state.dishwasher)state.dishwasher={has:null,status:'none'};return state.dishwasher}
function dishTask(){let d=dishState();if(d.has!==true)return null;let m={clean:['mcb_dishwasher_empty','Vaciar lavavajillas · vajilla limpia',10],dirty:['mcb_dishwasher_load','Cargar vajilla sucia en el lavavajillas',10],full:['mcb_dishwasher_start','Poner el lavavajillas',5],running:['mcb_dishwasher_empty','Vaciar lavavajillas cuando termine',10]}[d.status];return m?{id:m[0],area:'casa',text:m[1],min:m[2],priority:6,room:'cocina'}:null}
function wrapRaw(){if(typeof rawTasks!=='function'||rawTasks.__mcbSept)return;let old=rawTasks;window.rawTasks=function(){let a=old()||[],i=ironingTask(),d=dishTask();if(i&&!a.some(x=>x&&x.id===i.id)&&!state.done[i.id])a.push(i);if(d&&!a.some(x=>x&&x.id===d.id)&&!state.done[d.id])a.push(d);return a};window.rawTasks.__mcbSept=true}
function replan(){state.todayPlanDate='';state.planEngineVersion=VERSION;try{save();render()}catch(_){}setTimeout(renderExtras,0)}
function saveRawHome(h){localStorage.setItem('mcb_v2_home',JSON.stringify(h));let homes=[];try{homes=JSON.parse(localStorage.getItem('mcb_v2_homes')||'[]')}catch(_){}let i=homes.findIndex(x=>String(x.id)===String(h.id));if(i>=0)homes[i]=h;else if(h.id)homes.push(h);localStorage.setItem('mcb_v2_homes',JSON.stringify(homes))}
window.mcbWorkType=function(type){let h=rawHome();h.workSchedule=h.workSchedule||{type:'home',minutesByDay:{}};h.workSchedule.type=type;if(type==='work'&&!Object.keys(h.workSchedule.minutesByDay||{}).length)h.workSchedule.minutesByDay={'1':240,'2':240,'3':240,'4':240,'5':240};saveRawHome(h);replan()};window.mcbWorkMinutes=function(day,min){let h=rawHome();h.workSchedule=h.workSchedule||{type:'work',minutesByDay:{}};h.workSchedule.type='work';h.workSchedule.minutesByDay=h.workSchedule.minutesByDay||{};h.workSchedule.minutesByDay[String(day)]=Math.max(0,Number(min)||0);saveRawHome(h);replan()};window.mcbIroningMinutes=function(v){state.ironingMinutes=Math.max(15,Number(v)||60);delete state.done.mcb_ironing;replan()};
window.mcbDishHas=function(v){let d=dishState();d.has=v;if(!v)d.status='none';replan()};window.mcbDishStatus=function(v){let d=dishState();d.status=v;replan()};window.mcbDishStarted=function(){let d=dishState();state.done=state.done||{};state.done.mcb_dishwasher_start=true;d.status='running';d.startedAt=Date.now();replan()};window.mcbDishEmptied=function(){let d=dishState();state.done=state.done||{};state.done.mcb_dishwasher_empty=true;d.status='none';d.startedAt=null;replan()};
function renderDay(){let host=document.getElementById('todayContent');if(!host)return;let old=document.getElementById('mcbDayTitle');if(!old){old=document.createElement('div');old.id='mcbDayTitle';old.className='mcb-day-title';host.parentNode.insertBefore(old,host)}old.textContent='📅 '+todayName()+' · tareas a realizar'}
function renderWorkSchedule(){let list=document.getElementById('houseList');if(!list)return;let old=document.getElementById('mcbWorkSchedule');if(old)old.remove();let h=rawHome(),w=h.workSchedule||{type:'home',minutesByDay:{}},work=w.type==='work',box=document.createElement('div');box.id='mcbWorkSchedule';box.className='card';box.innerHTML='<h2>🧹 '+(work?'Vivienda de trabajo':'Mi hogar')+'</h2>';list.parentNode.insertBefore(box,list)}
function renderIroning(){document.getElementById('mcbIroningTime')?.remove()}
function renderDish(){let list=document.getElementById('houseList');if(!list)return;document.getElementById('mcbDishCard')?.remove();let d=dishState(),box=document.createElement('div');box.id='mcbDishCard';box.className='card';let status='';if(d.has===true){if(d.status==='full')status='<div class="softbox" style="margin-top:9px"><b>Está lleno.</b> La tarea es ponerlo en marcha.<div style="margin-top:8px"><button class="btn" onclick="mcbDishStarted()">▶ Lo pongo ahora</button></div></div>';else if(d.status==='running')status='<div class="softbox" style="margin-top:9px"><b>🫧 Lavavajillas puesto.</b><div class="meta">Cuando termine, quedará pendiente vaciarlo.</div><div style="margin-top:8px"><button class="btn soft" onclick="mcbDishStatus(\'clean\')">✓ Ya ha terminado</button></div></div>';else if(d.status==='clean')status='<div class="softbox" style="margin-top:9px"><b>Está limpio: toca vaciarlo.</b><div style="margin-top:8px"><button class="btn" onclick="mcbDishEmptied()">✓ Ya lo he vaciado</button></div></div>';else status='<div class="mcb-appliance-actions"><button class="chip '+(d.status==='dirty'?'on':'')+'" onclick="mcbDishStatus(\'dirty\')">Hay vajilla sucia</button><button class="chip" onclick="mcbDishStatus(\'full\')">Está lleno</button><button class="chip '+(d.status==='none'?'on':'')+'" onclick="mcbDishStatus(\'none\')">Nada pendiente</button></div>'}box.innerHTML='<h2>🍽️ Lavavajillas y cacharros</h2><div class="mcb-appliance-actions"><button class="chip '+(d.has===true?'on':'')+'" onclick="mcbDishHas(true)">Sí, hay lavavajillas</button><button class="chip '+(d.has===false?'on':'')+'" onclick="mcbDishHas(false)">No hay</button></div>'+status;list.parentNode.insertBefore(box,list)}
function pack(){let id=localStorage.getItem('mcb_v2_active_home'),homes=JSON.parse(localStorage.getItem('mcb_v2_homes')||'[]'),h=homes.find(x=>String(x.id)===String(id))||rawHome();return{v:1,home:h,today:state,house:house,laundry:laundry,shop:shop,people:people}}
window.mcbExportHome=async function(){let e=document.getElementById('mcbTransferText'),txt=btoa(unescape(encodeURIComponent(JSON.stringify(pack()))));if(e)e.value=txt;try{await navigator.clipboard.writeText(txt);alert('Código copiado. Pégalo en el otro móvil.')}catch(_){alert('Código preparado. Cópialo y llévalo al otro móvil.')}};window.mcbImportHome=function(){let e=document.getElementById('mcbTransferText');try{let p=JSON.parse(decodeURIComponent(escape(atob((e.value||'').trim())))),h=p.home;if(!h||!h.id)throw 0;let homes=JSON.parse(localStorage.getItem('mcb_v2_homes')||'[]'),i=homes.findIndex(x=>String(x.id)===String(h.id));if(i<0)homes.push(h);else homes[i]=h;localStorage.setItem('mcb_v2_homes',JSON.stringify(homes));localStorage.setItem('mcb_v2_active_home',h.id);localStorage.setItem('mcb_v2_home',JSON.stringify(h));[['today',p.today],['house',p.house],['laundry',p.laundry],['shop',p.shop],['people',p.people]].forEach(x=>{if(x[1])localStorage.setItem('mcb_home_'+h.id+'_'+x[0],JSON.stringify(x[1]))});location.href='./index.html?home='+encodeURIComponent(h.id)+'&v=21'}catch(_){alert('Ese código no es válido.')}};
function renderTransfer(){let list=document.getElementById('houseList');if(!list)return;document.getElementById('mcbTransferCard')?.remove();let box=document.createElement('div');box.id='mcbTransferCard';box.className='card';box.innerHTML='<h2>📱 Pasar esta casa a otro móvil</h2><div class="mcb-appliance-actions"><button class="btn" onclick="mcbExportHome()">Copiar código</button><button class="mini" onclick="mcbImportHome()">Importar código</button></div><textarea id="mcbTransferText" class="mcb-transfer" placeholder="Pega aquí el código"></textarea>';list.parentNode.insertBefore(box,list.nextSibling)}
function renderExtras(){renderDay();renderIroning();renderWorkSchedule();renderDish();renderTransfer()}
function start(){addStyles();wrapTaskHTML();wrapRaw();if(state.planEngineVersion!==VERSION)replan();else{try{render()}catch(_){}renderExtras()}let oldRender=window.render;if(typeof oldRender==='function'&&!oldRender.__mcbSept){window.render=function(){let r=oldRender.apply(this,arguments);setTimeout(renderExtras,0);return r};window.render.__mcbSept=true}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();