/* Mi casa, mi ritmo · realidad al llegar, cuidados y carga del hogar */
(function(){'use strict';
function cfgSafe(){try{return typeof cfg==='function'?(cfg()||{}):{}}catch(e){return{}}}
function dk(){let d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function arrival(){if(!state.arrival||state.arrival.date!==dk())state.arrival={date:dk(),minutes:0,items:[]};return state.arrival}
const HOUSE_PRESETS=[['Zapatos / entrada por recoger',8],['Ropa tendida por recoger',10],['Doblar ropa',15],['Tratar manchas',15],['Preparar / poner lavadora',10],['Recogida extra',15]];
function carePresets(){let r=cfgSafe().residents||{},out=[];if((Number(r.children)||0)+(Number(r.babies)||0)>0)out.push(['Llevar niños al cole / guardería',30],['Recoger niños del cole / guardería',30]);if(Number(r.seniors)||0>0)out.push(['Acompañar a una persona mayor',30],['Paseo con una persona mayor',30]);out.push(['Recado o desplazamiento de la casa',20]);return out}
function residentLoad(){let c=cfgSafe(),r=c.residents;if(r)return (Number(r.adults)||0)*.55+(Number(r.teens)||0)*.75+(Number(r.children)||0)*1.25+(Number(r.babies)||0)*1.6+(Number(r.seniors)||0)*.65;let ps=c.people||[],score=0;ps.forEach(p=>{let x=p.role||'Adulto';score+=x==='Bebé'?1.6:x==='Niño'?1.25:x==='Adolescente'?.75:x==='Persona mayor'?.65:.55});return score}
function loadExtras(){let s=residentLoad(),out=[];if(s>=2.5)out.push({id:'load_pickup',area:'casa',text:'Recogida extra por uso de la casa',min:Math.min(25,10+Math.round(s*3)),priority:7,room:'entrada'});if(s>=3)out.push({id:'load_laundry',area:'colada',text:'Revisar ropa y coladas acumuladas',min:10,priority:8,essential:true});return out}
function wrapRaw(){if(typeof rawTasks!=='function'||rawTasks.__arrival)return;let old=rawTasks;window.rawTasks=function(){let a=old()||[],x=loadExtras();x.forEach(t=>{if(!a.some(y=>y&&y.id===t.id))a.push(t)});return a};window.rawTasks.__arrival=true}
function totalMinutes(){let c=cfgSafe();return Number(c.organization&&c.organization.minutes)||75}
function remaining(){return Math.max(0,totalMinutes()-arrival().minutes)}
function trimPlan(){if(!Array.isArray(state.todayPlan)||typeof rawTasks!=='function')return;let map=new Map((rawTasks()||[]).filter(Boolean).map(t=>[t.id,t])),ids=[...state.todayPlan],limit=remaining(),used=ids.reduce((s,id)=>s+Number((map.get(id)||{}).min||0),0);if(used<=limit)return;for(let i=ids.length-1;i>=0&&used>limit;i--){let t=map.get(ids[i]);if(!t)continue;let keep=t.mustToday||t.essential||t.text==='Hacer camas'||(Array.isArray(state.manualToday)&&state.manualToday.includes(t.id));if(keep)continue;used-=Number(t.min)||0;ids.splice(i,1)}state.todayPlan=ids}
function invalidate(){state.todayPlanDate='';try{save()}catch(_){}try{render()}catch(_){}trimPlan();try{save();render()}catch(_){}renderBox()}
function addItem(text,min){let a=arrival();a.items.push({id:'arr_'+Date.now(),text:text,min:min});a.minutes+=min;invalidate()}
function addHouse(i){let p=HOUSE_PRESETS[i];if(p)addItem(p[0],p[1])}
function addCare(i){let p=carePresets()[i];if(p)addItem(p[0],p[1])}
function addMinutes(){let e=document.getElementById('mcbArrivalMinutes'),v=Math.max(0,Number(e&&e.value)||0);if(!v)return;addItem('Otro trabajo, cuidado o desplazamiento',v);e.value=''}
function clearArrival(){state.arrival={date:dk(),minutes:0,items:[]};invalidate()}
function renderBox(){let hoy=document.getElementById('hoy');if(!hoy)return;let box=document.getElementById('mcbArrivalBox');if(!box){box=document.createElement('div');box.id='mcbArrivalBox';box.className='card';let content=document.getElementById('todayContent');hoy.insertBefore(box,content||hoy.firstChild)}let a=arrival(),house=HOUSE_PRESETS.map((p,i)=>'<button class="chip" onclick="mcbArrivalHouse('+i+')">＋ '+p[0]+'</button>').join(''),care=carePresets().map((p,i)=>'<button class="chip" onclick="mcbArrivalCare('+i+')">＋ '+p[0]+'</button>').join('');box.innerHTML='<h2>⏱️ Tiempo ocupado hoy</h2><div class="meta" style="margin:6px 0 10px">Aquí cuenta todo el trabajo real: lo que encuentras al llegar, cuidados, acompañamientos y desplazamientos. La app descuenta ese tiempo y reajusta lo que queda.</div><div class="muted" style="margin-bottom:6px"><b>🚪 Lo que me encuentro al llegar</b></div><div class="chips">'+house+'</div><div class="muted" style="margin:12px 0 6px"><b>👨‍👩‍👧 Cuidados y desplazamientos</b></div><div class="chips">'+care+'</div><div class="quick" style="margin-top:10px"><input id="mcbArrivalMinutes" class="field" type="number" min="1" placeholder="Otros minutos empleados"><button class="btn" onclick="mcbArrivalAddMinutes()">Añadir</button></div>'+(a.minutes?'<div class="softbox" style="margin-top:10px"><b>⏱️ Ya empleados: '+a.minutes+' min</b><div class="meta">Tiempo orientativo restante: '+remaining()+' min</div>'+(a.items.length?'<div class="meta" style="margin-top:6px">'+a.items.map(x=>'• '+esc(x.text)+' · '+x.min+' min').join('<br>')+'</div>':'')+'<button class="mini" style="margin-top:8px" onclick="mcbArrivalClear()">Reiniciar tiempo ocupado</button></div>':'')}
window.mcbArrivalPreset=addHouse;window.mcbArrivalHouse=addHouse;window.mcbArrivalCare=addCare;window.mcbArrivalAddMinutes=addMinutes;window.mcbArrivalClear=clearArrival;
function start(){wrapRaw();renderBox();let sig=''+residentLoad();if(state.residentLoadSig!==sig){state.residentLoadSig=sig;state.todayPlanDate='';try{save();render()}catch(_){}}if(arrival().minutes)trimPlan()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();