/* Mi casa, mi ritmo · mejoras de uso real septiembre 2026 */
(function(){'use strict';
const VERSION='2026-09-06-real-work-v1';
function c(){try{return typeof cfg==='function'?(cfg()||{}):{}}catch(e){return{}}}
function todayName(){return new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).replace(/^./,x=>x.toUpperCase())}
function addStyles(){if(document.getElementById('mcbSeptStyles'))return;let s=document.createElement('style');s.id='mcbSeptStyles';s.textContent='.chips{display:flex!important;flex-wrap:wrap!important;overflow:visible!important}.chip{white-space:normal!important;text-align:center}.mcb-day-title{margin:0 0 12px;padding:12px 14px;background:#e8eee2;border-radius:14px;font-weight:900;font-size:18px;color:#58704f}.mcb-appliance-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}';document.head.appendChild(s)}
function labelTask(t){if(!t)return t;let room={dorm:'dormitorio',salon:'salón',entrada:'entrada',cocina:'cocina',bano:'baño'}[t.room];if(room&&['Polvo','Recogida','Suelo','Aspirar/barrer','Ventilar'].includes(t.text))return Object.assign({},t,{text:t.text+' · '+room});return t}
function wrapTaskHTML(){if(typeof taskHTML!=='function'||taskHTML.__mcbSept)return;let old=taskHTML;window.taskHTML=function(t){return old(labelTask(t))};window.taskHTML.__mcbSept=true}
function ironingTask(){let x=c().laundry||{},v=String(x.ironing||'').toLowerCase();if(!v||v==='no')return null;return{id:'mcb_ironing',area:'colada',text:'Planchar ropa',min:v.includes('bastante')?35:20,priority:4,room:'colada'} }
function dishState(){if(!state.dishwasher)state.dishwasher={has:null,status:'none'};return state.dishwasher}
function dishTask(){let d=dishState();if(d.has!==true)return null;let m={clean:'Vaciar lavavajillas · vajilla limpia',dirty:'Meter vajilla sucia en el lavavajillas',full:'Poner el lavavajillas'}[d.status];return m?{id:'mcb_dishwasher_'+d.status,area:'casa',text:m,min:10,priority:6,room:'cocina'}:null}
function wrapRaw(){if(typeof rawTasks!=='function'||rawTasks.__mcbSept)return;let old=rawTasks;window.rawTasks=function(){let a=old()||[],i=ironingTask(),d=dishTask();if(i&&!a.some(x=>x&&x.id===i.id)&&!state.done[i.id])a.push(i);if(d&&!a.some(x=>x&&x.id===d.id)&&!state.done[d.id])a.push(d);return a};window.rawTasks.__mcbSept=true}
function replan(){state.todayPlanDate='';state.planEngineVersion=VERSION;try{save();render()}catch(_){}setTimeout(renderExtras,0)}
window.mcbDishHas=function(v){let d=dishState();d.has=v;if(!v)d.status='none';replan()};window.mcbDishStatus=function(v){let d=dishState();d.status=v;['clean','dirty','full'].forEach(x=>delete state.done['mcb_dishwasher_'+x]);replan()};
function renderDay(){let host=document.getElementById('todayContent');if(!host)return;let old=document.getElementById('mcbDayTitle');if(!old){old=document.createElement('div');old.id='mcbDayTitle';old.className='mcb-day-title';host.parentNode.insertBefore(old,host)}old.textContent='📅 '+todayName()+' · tareas a realizar'}
function renderDish(){let list=document.getElementById('houseList');if(!list)return;let old=document.getElementById('mcbDishCard');if(old)old.remove();let d=dishState(),box=document.createElement('div');box.id='mcbDishCard';box.className='card';box.innerHTML='<h2>🍽️ Lavavajillas y cacharros</h2><div class="meta" style="margin:6px 0">Indica si esta casa tiene lavavajillas. Si lo tiene, marca cómo te lo encuentras y Hoy generará la tarea.</div><div class="mcb-appliance-actions"><button class="chip '+(d.has===true?'on':'')+'" onclick="mcbDishHas(true)">Sí, hay lavavajillas</button><button class="chip '+(d.has===false?'on':'')+'" onclick="mcbDishHas(false)">No hay</button></div>'+(d.has===true?'<div class="mcb-appliance-actions"><button class="chip '+(d.status==='clean'?'on':'')+'" onclick="mcbDishStatus(\'clean\')">Limpio: vaciar</button><button class="chip '+(d.status==='dirty'?'on':'')+'" onclick="mcbDishStatus(\'dirty\')">Hay vajilla sucia</button><button class="chip '+(d.status==='full'?'on':'')+'" onclick="mcbDishStatus(\'full\')">Lleno: ponerlo</button><button class="chip '+(d.status==='none'?'on':'')+'" onclick="mcbDishStatus(\'none\')">Nada pendiente</button></div>':'<div class="meta" style="margin-top:8px">Sin lavavajillas, el fregado de cacharros se considera trabajo de cocina.</div>');list.parentNode.insertBefore(box,list)}
function renderExtras(){renderDay();renderDish()}
function start(){addStyles();wrapTaskHTML();wrapRaw();if(state.planEngineVersion!==VERSION)replan();else{try{render()}catch(_){}renderExtras()}let oldRender=window.render;if(typeof oldRender==='function'&&!oldRender.__mcbSept){window.render=function(){let r=oldRender.apply(this,arguments);setTimeout(renderExtras,0);return r};window.render.__mcbSept=true}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();