/* Mi casa, mi ritmo · ciclo de 4 semanas, puntuales, informes e instalación */
(function(){'use strict';
const WEEK_THEMES={
1:{name:'Detalles y puertas',items:['Puerta de entrada: marco, manilla e interruptores','Juntas, esquinas y puntos de cal','Puertas, marcos, manillas e interruptores','Sofá a fondo: huecos, estructura y patas','Microondas por dentro + pequeños electrodomésticos','Rodapiés de la zona más usada','Cristales de una zona pequeña + carriles']},
2:{name:'Rodapiés y ventanas',items:['Rodapiés de entrada y pasillos','Interior de un mueble o cajones de baño','Rodapiés + exterior de canapés','Cristales de salón/comedor + carriles','Horno si lo necesita','Marcos de ventanas de una zona','Puertas interiores de una zona']},
3:{name:'Partes altas',items:['Techos, esquinas altas y radiador','Azulejos altos de una zona','Partes superiores de armarios + lámparas','Lámparas + decoración','Frigorífico por zonas','Parte alta de muebles de cocina','Revisión de polvo en zonas poco accesibles']},
4:{name:'Interiores',items:['Cristales de otra zona + carriles','Radiador + puerta de baño','Interior de mesilla o cajonera','Textiles de sofá + entrada','Armarios o cajones + zócalos','Interior de un armario pequeño','Repaso de una zona olvidada']}
};
function homeId(){return localStorage.getItem('mcb_v2_active_home')||'default'}
function homeCfg(){try{return typeof cfg==='function'?(cfg()||{}):{}}catch(e){return{}}}
function hkey(){return'mcb_home_'+homeId()+'_history'}
function history(){try{return JSON.parse(localStorage.getItem(hkey())||'{"days":{}}')}catch(e){return{days:{}}}}
function saveHistory(h){localStorage.setItem(hkey(),JSON.stringify(h))}
function iso(d=new Date()){let z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)}
function monday(d=new Date()){let x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function cycleAnchor(){let k='mcb_home_'+homeId()+'_cycle_anchor',v=localStorage.getItem(k);if(!v){v=iso(monday());localStorage.setItem(k,v)}return v}
function cycleWeek(d=new Date()){let a=new Date(cycleAnchor()+'T12:00'),m=monday(d),n=Math.floor((m-a)/(7*86400000));return((n%4)+4)%4+1}
function workDays(){let a=homeCfg().organization&&homeCfg().organization.days;return Array.isArray(a)&&a.length?a:[1,2,3,4,5,6,0]}
function sortedDays(){return[1,2,3,4,5,6,0].filter(d=>workDays().includes(d))}
function dayLabel(d){return({1:'Lunes',2:'Martes',3:'Miércoles',4:'Jueves',5:'Viernes',6:'Sábado',0:'Domingo'})[d]}
function canonicalCycleId(text,w,d){let s=text.toLowerCase();if(s.includes('microondas'))return'hp_micro';if(s.includes('horno'))return'hp_horno';if(s.includes('frigorífico'))return'hp_frigo';if(s.includes('rodapiés'))return'hp_rodapies';if(s.includes('cristales'))return'hp_cristales';if(s.includes('partes superiores')||s.includes('partes altas')||s.includes('techos, esquinas altas')||s.includes('lámparas'))return'hp_altas';return'cycle_w'+w+'_d'+d}
function rotationTask(date=new Date()){let days=sortedDays(),idx=days.indexOf(date.getDay());if(idx<0)return null;let w=cycleWeek(date),theme=WEEK_THEMES[w],text=theme.items[idx%theme.items.length];return{id:canonicalCycleId(text,w,date.getDay()),area:'casa',text:'🔄 '+text,min:15,priority:1,room:'periodicas',cycle:true}}
function allRotationForWeek(w){let theme=WEEK_THEMES[w];return sortedDays().map((d,i)=>({day:d,label:dayLabel(d),text:theme.items[i%theme.items.length]}))}
function rawMap(){let list=[];try{list=typeof rawTasks==='function'?rawTasks():[]}catch(e){}return new Map((list||[]).filter(Boolean).map(t=>[t.id,t]))}
function quickTasks(){return Array.isArray(state.quick)?state.quick:[]}
function installRawTasks(){if(typeof rawTasks!=='function'||rawTasks.__mcbCycle)return;let old=rawTasks;window.rawTasks=function(){let out=old();return(out||[]).concat(quickTasks())};window.rawTasks.__mcbCycle=true}
function installHouseTasks(){if(typeof houseTasks!=='function'||houseTasks.__mcbCycle)return;let old=houseTasks;window.houseTasks=function(){let out=old()||[],r=rotationTask();if(r&&!out.some(t=>t&&t.id===r.id))out.push(r);return out};window.houseTasks.__mcbCycle=true}
function recordPlanFor(dateKey){let h=history(),rec=h.days[dateKey]||{planned:[],done:[]},map=rawMap(),ids=Array.isArray(state.todayPlan)?[...new Set(state.todayPlan)]:[];let planned=ids.map(id=>map.get(id)).filter(Boolean).map(t=>({id:t.id,text:t.text,min:Number(t.min)||0}));rec.planned=planned;rec.done=[...new Set(planned.filter(t=>state.done&&state.done[t.id]).map(t=>t.id))];rec.updated=Date.now();h.days[dateKey]=rec;saveHistory(h)}
function rolloverDay(){if(typeof state==='undefined')return;let today=iso(),prev=state.historyDay;if(!prev){state.historyDay=today;try{save()}catch(_){}return}if(prev===today)return;recordPlanFor(prev);state.done={};state.quick=[];state.manualToday=[];state.todayPlan=[];state.todayPlanDate='';state.historyDay=today;try{save()}catch(_){}}
function ensureRotationInPlan(){let r=rotationTask();if(!r||typeof state==='undefined'||(state.done&&state.done[r.id]))return;state.todayPlan=Array.isArray(state.todayPlan)?state.todayPlan:[];if(!state.todayPlan.includes(r.id)){state.todayPlan.push(r.id);try{save()}catch(_){}}}
function addQuick(){let e=document.getElementById('mcbQuickInput');if(!e)return;let text=e.value.trim();if(!text)return;state.quick=quickTasks();let q={id:'quick_'+Date.now(),area:'casa',text:text,min:10,priority:10,manual:true,date:iso()};state.quick.push(q);state.manualToday=Array.isArray(state.manualToday)?state.manualToday:[];if(!state.manualToday.includes(q.id))state.manualToday.push(q.id);state.todayPlan=Array.isArray(state.todayPlan)?state.todayPlan:[];if(!state.todayPlan.includes(q.id))state.todayPlan.push(q.id);delete state.done[q.id];e.value='';try{save()}catch(_){}snapshotToday();try{render()}catch(_){}ensureQuickBox()}
function ensureQuickBox(){let hoy=document.getElementById('hoy'),content=document.getElementById('todayContent');if(!hoy||!content)return;let box=document.getElementById('mcbQuickBox');if(!box){box=document.createElement('div');box.id='mcbQuickBox';box.className='card';box.innerHTML='<div class="muted">➕ HA SURGIDO ALGO</div><div class="quick"><input id="mcbQuickInput" class="field" placeholder="Tarea puntual"><button class="btn" id="mcbQuickAdd">Añadir</button></div><div class="meta" style="margin-top:8px">Se añade solo a hoy. No reorganiza el resto del día.</div>';let notice=hoy.querySelector('.notice');hoy.insertBefore(box,notice||null);box.querySelector('#mcbQuickAdd').onclick=addQuick;box.querySelector('#mcbQuickInput').addEventListener('keydown',e=>{if(e.key==='Enter')addQuick()})}}
function snapshotToday(){if(typeof state==='undefined')return;recordPlanFor(iso())}
function wrapComplete(){if(typeof completeTask!=='function'||completeTask.__mcbReport)return;let old=completeTask;window.completeTask=function(id,v){if(id&&id.startsWith('hp_')){house.periodic=house.periodic||{};let k=id.slice(3);if(v)house.periodic[k]=Object.assign({},house.periodic[k],{last:Date.now()});else delete house.periodic[k]}old(id,v);snapshotToday();renderReports()};window.completeTask.__mcbReport=true}
function rangeDays(start,end){let out=[],d=new Date(start);d.setHours(12,0,0,0);let e=new Date(end);e.setHours(12,0,0,0);while(d<=e){out.push(iso(d));d.setDate(d.getDate()+1)}return out}
function reportFor(days){let h=history(),planned=[],done=[];days.forEach(k=>{let r=h.days[k];if(!r)return;(r.planned||[]).forEach(t=>planned.push({...t,date:k}));(r.done||[]).forEach(id=>done.push(k+'|'+id))});let pending=planned.filter(t=>!done.includes(t.date+'|'+t.id));return{planned,doneCount:done.length,pending}}
function reportCard(title,days){let r=reportFor(days),total=r.planned.length,done=r.doneCount,p=r.pending;return'<div class="card"><h2>'+title+'</h2><div class="summaryGrid"><div class="summary"><span class="muted">Hechas</span><b>'+done+'</b></div><div class="summary"><span class="muted">Sin hacer</span><b>'+p.length+'</b></div></div>'+(p.length?'<div class="meta" style="margin-top:10px"><b>Quedó pendiente:</b><br>'+p.slice(0,8).map(x=>'• '+esc(x.text)).join('<br>')+(p.length>8?'<br>… y '+(p.length-8)+' más':'')+'</div>':'<div class="meta" style="margin-top:10px">🎉 Nada pendiente en este periodo.</div>')+(total?'<div class="meta" style="margin-top:7px">'+done+' de '+total+' tareas registradas.</div>':'<div class="meta" style="margin-top:7px">El informe empezará a llenarse desde ahora.</div>')+'</div>'}
function renderReports(){let host=document.getElementById('mcbReports');if(!host)return;let now=new Date(),mon=monday(now),sun=new Date(mon);sun.setDate(sun.getDate()+6);let ms=new Date(now.getFullYear(),now.getMonth(),1),me=new Date(now.getFullYear(),now.getMonth()+1,0);host.innerHTML=reportCard('📍 Hoy',[iso(now)])+reportCard('📅 Esta semana',rangeDays(mon,sun))+reportCard('🗓️ Este mes',rangeDays(ms,me))+'<div class="notice">Lo que no se hizo queda registrado, pero no se amontona automáticamente para mañana.</div>'}
function planHTML(){let w=cycleWeek();let cards=[1,2,3,4].map(n=>{let t=WEEK_THEMES[n],rows=allRotationForWeek(n).map(x=>'<div class="item"><b>'+x.label+'</b><div class="muted">'+esc(x.text)+'</div></div>').join('');return'<details class="card" '+(n===w?'open':'')+'><summary><b>Semana '+n+' · '+t.name+'</b>'+(n===w?' <span class="pill">Esta semana</span>':'')+'</summary><div style="margin-top:9px">'+rows+'</div></details>'}).join('');return'<div class="softbox" style="margin-bottom:12px"><b>4 semanas, sin pensar qué toca.</b><div class="meta">La app coloca una tarea de detalle en cada día que hayas marcado para limpiar.</div></div>'+cards}
function ensureCasaExtras(){let casa=document.getElementById('casa');if(!casa)return;if(!document.getElementById('mcbCyclePlan')){let p=document.createElement('div');p.id='mcbCyclePlan';p.innerHTML='<div class="sectionTitle"><h2>📅 Plan de 4 semanas</h2></div>'+planHTML();casa.appendChild(p)}if(!document.getElementById('mcbReports')){let h=document.createElement('div');h.id='mcbReports';h.innerHTML='<div class="sectionTitle"><h2>📊 Informes</h2></div>';casa.appendChild(h)}if(!document.getElementById('mcbInstall')){let i=document.createElement('div');i.id='mcbInstall';i.className='card';i.innerHTML='<h2>📲 Instalar aplicación</h2><div class="muted" id="mcbInstallText">En Chrome: ⋮ → Instalar aplicación o Añadir a pantalla de inicio.</div><button class="btn soft" id="mcbInstallBtn" style="margin-top:10px;display:none">Instalar ahora</button>';casa.appendChild(i)}renderReports()}
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;let b=document.getElementById('mcbInstallBtn');if(b)b.style.display='inline-block'});window.addEventListener('appinstalled',()=>{let t=document.getElementById('mcbInstallText'),b=document.getElementById('mcbInstallBtn');if(t)t.textContent='✅ Aplicación instalada.';if(b)b.style.display='none'});
function wireInstall(){let b=document.getElementById('mcbInstallBtn');if(b&&!b.dataset.wired){b.dataset.wired='1';b.onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();try{await installPrompt.userChoice}catch(_){}installPrompt=null;b.style.display='none'}}}
function enablePwa(){if(!document.querySelector('link[rel="manifest"]')){let l=document.createElement('link');l.rel='manifest';l.href='manifest.webmanifest';document.head.appendChild(l)}if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
function refresh(){installRawTasks();installHouseTasks();rolloverDay();ensureRotationInPlan();wrapComplete();ensureQuickBox();ensureCasaExtras();wireInstall();snapshotToday();try{render()}catch(_){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh);else refresh();enablePwa();
})();