/* Mi casa, mi ritmo · mejoras de uso real septiembre 2026 */
(function(){'use strict';
const VERSION='2026-09-17-professional-schedule-v4';
const rawCfg=typeof cfg==='function'?cfg:null;
function rawHome(){try{return rawCfg?(rawCfg()||{}):{}}catch(e){return{}}}
function todayWorkMinutes(h){let w=h.workSchedule||{},d=String(new Date().getDay());return w.type==='work'?Math.max(0,Number((w.minutesByDay||{})[d])||0):null}
if(rawCfg&&!rawCfg.__mcbWork){window.cfg=function(){let h=rawHome(),m=todayWorkMinutes(h);if(m!==null){h=JSON.parse(JSON.stringify(h));h.organization=h.organization||{};h.organization.minutes=m||10;h.organization.days=Object.keys((h.workSchedule&&h.workSchedule.minutesByDay)||{}).filter(k=>Number(h.workSchedule.minutesByDay[k])>0).map(Number)}return h};window.cfg.__mcbWork=true}
function c(){try{return typeof cfg==='function'?(cfg()||{}):{}}catch(e){return{}}}
function todayName(){return new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).replace(/^./,x=>x.toUpperCase())}
function addStyles(){if(document.getElementById('mcbSeptStyles'))return;let s=document.createElement('style');s.id='mcbSeptStyles';s.textContent='.chips{display:flex!important;flex-wrap:wrap!important;overflow:visible!important}.chip{white-space:normal!important;text-align:center}.mcb-day-title{margin:0 0 12px;padding:12px 14px;background:#e8eee2;border-radius:14px;font-weight:900;font-size:18px;color:#58704f}.mcb-appliance-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.mcb-transfer{width:100%;min-height:80px;margin-top:8px;padding:10px;border:1px solid #e8e1d7;border-radius:12px}.mcb-schedule-row{display:grid;grid-template-columns:95px 1fr;gap:9px;align-items:center;margin:7px 0}.mcb-schedule-row select{width:100%;padding:9px;border:1px solid #e8e1d7;border-radius:11px;background:#fff}';document.head.appendChild(s)}
function labelTask(t){if(!t)return t;let room={dorm:'dormitorio',salon:'salón',entrada:'entrada',cocina:'cocina',bano:'baño'}[t.room];if(room&&['Polvo','Recogida','Suelo','Suelo · mopa/fregona','Aspirar/barrer','Ventilar'].includes(t.text))return Object.assign({},t,{text:t.text+' · '+room});return t}
function wrapTaskHTML(){if(typeof taskHTML!=='function'||taskHTML.__mcbSept)return;let old=taskHTML;window.taskHTML=function(t){return old(labelTask(t))};window.taskHTML.__mcbSept=true}
function ironingTask(){let x=c().laundry||{},v=String(x.ironing||'').toLowerCase();if(!v||v==='no')return null;let min=Math.max(15,Number(state.ironingMinutes)||0);if(!min)min=v.includes('bastante')?180:60;return{id:'mcb_ironing',area:'colada',text:'Planchar ropa',min:min,priority:4,room:'colada'} }
function dishState(){if(!state.dishwasher)state.dishwasher={has:null,status:'none'};return state.dishwasher}
function dishTask(){let d=dishState();if(d.has!==true)return null;let m={clean:'Vaciar lavavajillas · vajilla limpia',dirty:'Meter vajilla sucia en el lavavajillas',full:'Poner el lavavajillas'}[d.status];return m?{id:'mcb_dishwasher_'+d.status,area:'casa',text:m,min:10,priority:6,room:'cocina'}:null}
function wrapRaw(){if(typeof rawTasks!=='function'||rawTasks.__mcbSept)return;let old=rawTasks;window.rawTasks=function(){let a=old()||[],i=ironingTask(),d=dishTask();if(i&&!a.some(x=>x&&x.id===i.id)&&!state.done[i.id])a.push(i);if(d&&!a.some(x=>x&&x.id===d.id)&&!state.done[d.id])a.push(d);return a};window.rawTasks.__mcbSept=true}
function replan(){state.todayPlanDate='';state.planEngineVersion=VERSION;try{save();render()}catch(_){}setTimeout(renderExtras,0)}
function saveRawHome(h){localStorage.setItem('mcb_v2_home',JSON.stringify(h));let homes=[];try{homes=JSON.parse(localStorage.getItem('mcb_v2_homes')||'[]')}catch(_){}let i=homes.findIndex(x=>String(x.id)===String(h.id));if(i>=0)homes[i]=h;else if(h.id)homes.push(h);localStorage.setItem('mcb_v2_homes',JSON.stringify(homes))}
window.mcbWorkType=function(type){let h=rawHome();h.workSchedule=h.workSchedule||{type:'home',minutesByDay:{}};h.workSchedule.type=type;if(type==='work'&&!Object.keys(h.workSchedule.minutesByDay||{}).length){h.workSchedule.minutesByDay={'1':240,'2':240,'3':240,'4':240,'5':240}}saveRawHome(h);replan()};
window.mcbWorkMinutes=function(day,min){let h=rawHome();h.workSchedule=h.workSchedule||{type:'work',minutesByDay:{}};h.workSchedule.type='work';h.workSchedule.minutesByDay=h.workSchedule.minutesByDay||{};h.workSchedule.minutesByDay[String(day)]=Math.max(0,Number(min)||0);saveRawHome(h);replan()};
window.mcbIroningMinutes=function(v){state.ironingMinutes=Math.max(15,Number(v)||60);delete state.done.mcb_ironing;replan()};
window.mcbDishHas=function(v){let d=dishState();d.has=v;if(!v)d.status='none';replan()};window.mcbDishStatus=function(v){let d=dishState();d.status=v;['clean','dirty','full'].forEach(x=>delete state.done['mcb_dishwasher_'+x]);replan()};
function renderDay(){let host=document.getElementById('todayContent');if(!host)return;let old=document.getElementById('mcbDayTitle');if(!old){old=document.createElement('div');old.id='mcbDayTitle';old.className='mcb-day-title';host.parentNode.insertBefore(old,host)}old.textContent='📅 '+todayName()+' · tareas a realizar'}
function renderWorkSchedule(){let list=document.getElementById('houseList');if(!list)return;let old=document.getElementById('mcbWorkSchedule');if(old)old.remove();let h=rawHome(),w=h.workSchedule||{type:'home',minutesByDay:{}},work=w.type==='work',days=[[1,'Lunes'],[2,'Martes'],[3,'Miércoles'],[4,'Jueves'],[5,'Viernes'],[6,'Sábado'],[0,'Domingo']],opts=[[0,'No voy'],[60,'1 h'],[90,'1 h 30'],[120,'2 h'],[150,'2 h 30'],[180,'3 h'],[210,'3 h 30'],[240,'4 h'],[270,'4 h 30'],[300,'5 h'],[360,'6 h'],[420,'7 h'],[480,'8 h']];let rows=work?days.map(d=>{let val=Number((w.minutesByDay||{})[d[0]])||0;return'<div class="mcb-schedule-row"><b>'+d[1]+'</b><select onchange="mcbWorkMinutes('+d[0]+',this.value)">'+opts.map(o=>'<option value="'+o[0]+'" '+(val===o[0]?'selected':'')+'>'+o[1]+'</option>').join('')+'</select></div>'}).join(''):'';let box=document.createElement('div');box.id='mcbWorkSchedule';box.className='card';box.innerHTML='<h2>🧹 ¿Esta vivienda es tu casa o tu trabajo?</h2><div class="meta" style="margin:6px 0 9px">Esto cambia cómo calcula la app el tiempo disponible. En una casa de trabajo puede haber un horario distinto cada día.</div><div class="chips"><button class="chip '+(!work?'on':'')+'" onclick="mcbWorkType(\'home\')">🏠 Es mi propio hogar</button><button class="chip '+(work?'on':'')+'" onclick="mcbWorkType(\'work\')">🧽 Trabajo limpiando aquí</button></div>'+(work?'<div class="softbox" style="margin-top:10px"><b>Horario semanal en esta vivienda</b><div class="meta" style="margin:4px 0 8px">Marca cuánto tiempo trabajas aquí cada día. «No voy» deja ese día fuera del plan.</div>'+rows+'</div>':'');list.parentNode.insertBefore(box,list)}
function renderIroning(){let hoy=document.getElementById('hoy'),content=document.getElementById('todayContent');if(!hoy||!content)return;let old=document.getElementById('mcbIroningTime');if(old)old.remove();let x=c().laundry||{},v=String(x.ironing||'').toLowerCase();if(!v||v==='no')return;let min=Math.max(15,Number(state.ironingMinutes)||0)||(v.includes('bastante')?180:60),box=document.createElement('div');box.id='mcbIroningTime';box.className='card';box.innerHTML='<h2>👔 ¿Cuánto planchado hay hoy?</h2><div class="meta" style="margin:6px 0 9px">El tiempo de plancha cuenta solo cuando lo eliges y con una duración realista para ese día.</div><div class="chips">'+[[30,'30 min'],[60,'1 h'],[90,'1 h 30'],[120,'2 h'],[150,'2 h 30'],[180,'3 h'],[210,'3 h 30']].map(x=>'<button class="chip '+(min===x[0]?'on':'')+'" onclick="mcbIroningMinutes('+x[0]+')">'+x[1]+'</button>').join('')+'</div>';hoy.insertBefore(box,content)}
function renderDish(){let list=document.getElementById('houseList');if(!list)return;let old=document.getElementById('mcbDishCard');if(old)old.remove();let d=dishState(),box=document.createElement('div');box.id='mcbDishCard';box.className='card';box.innerHTML='<h2>🍽️ Lavavajillas y cacharros</h2><div class="meta" style="margin:6px 0">Indica si esta casa tiene lavavajillas. Si lo tiene, marca cómo te lo encuentras y Hoy generará la tarea.</div><div class="mcb-appliance-actions"><button class="chip '+(d.has===true?'on':'')+'" onclick="mcbDishHas(true)">Sí, hay lavavajillas</button><button class="chip '+(d.has===false?'on':'')+'" onclick="mcbDishHas(false)">No hay</button></div>'+(d.has===true?'<div class="mcb-appliance-actions"><button class="chip '+(d.status==='clean'?'on':'')+'" onclick="mcbDishStatus(\'clean\')">Limpio: vaciar</button><button class="chip '+(d.status==='dirty'?'on':'')+'" onclick="mcbDishStatus(\'dirty\')">Hay vajilla sucia</button><button class="chip '+(d.status==='full'?'on':'')+'" onclick="mcbDishStatus(\'full\')">Lleno: ponerlo</button><button class="chip '+(d.status==='none'?'on':'')+'" onclick="mcbDishStatus(\'none\')">Nada pendiente</button></div>':'<div class="meta" style="margin-top:8px">Sin lavavajillas, el fregado de cacharros se considera trabajo de cocina.</div>');list.parentNode.insertBefore(box,list)}
function pack(){let id=localStorage.getItem('mcb_v2_active_home'),homes=JSON.parse(localStorage.getItem('mcb_v2_homes')||'[]'),h=homes.find(x=>String(x.id)===String(id))||rawHome();return{v:1,home:h,today:state,house:house,laundry:laundry,shop:shop,people:people}}
window.mcbExportHome=async function(){let e=document.getElementById('mcbTransferText'),txt=btoa(unescape(encodeURIComponent(JSON.stringify(pack()))));if(e)e.value=txt;try{await navigator.clipboard.writeText(txt);alert('Código copiado. Pégalo en el otro móvil.')}catch(_){alert('Código preparado. Cópialo y llévalo al otro móvil.')}};
window.mcbImportHome=function(){let e=document.getElementById('mcbTransferText');try{let p=JSON.parse(decodeURIComponent(escape(atob((e.value||'').trim())))),h=p.home;if(!h||!h.id)throw 0;let homes=JSON.parse(localStorage.getItem('mcb_v2_homes')||'[]'),i=homes.findIndex(x=>String(x.id)===String(h.id));if(i<0)homes.push(h);else homes[i]=h;localStorage.setItem('mcb_v2_homes',JSON.stringify(homes));localStorage.setItem('mcb_v2_active_home',h.id);localStorage.setItem('mcb_v2_home',JSON.stringify(h));[['today',p.today],['house',p.house],['laundry',p.laundry],['shop',p.shop],['people',p.people]].forEach(x=>{if(x[1])localStorage.setItem('mcb_home_'+h.id+'_'+x[0],JSON.stringify(x[1]))});alert('Casa copiada. Voy a abrirla.');location.href='./index.html?home='+encodeURIComponent(h.id)+'&v=12'}catch(_){alert('Ese código no es válido. Cópialo completo desde el otro móvil.')}};
function renderTransfer(){let list=document.getElementById('houseList');if(!list)return;let old=document.getElementById('mcbTransferCard');if(old)old.remove();let box=document.createElement('div');box.id='mcbTransferCard';box.className='card';box.innerHTML='<h2>📱 Pasar esta casa a otro móvil</h2><div class="meta" style="margin:6px 0">Copia la casa, sus tareas, coladas, compra y reparto al otro teléfono. No borra este móvil.</div><div class="mcb-appliance-actions"><button class="btn" onclick="mcbExportHome()">Copiar código</button><button class="mini" onclick="mcbImportHome()">Importar código</button></div><textarea id="mcbTransferText" class="mcb-transfer" placeholder="Aquí aparecerá el código, o pega aquí el del otro móvil"></textarea><div class="meta">Esto sirve para traspasar los datos. La sincronización automática entre móviles necesitará una cuenta/nube y será un paso posterior.</div>';list.parentNode.insertBefore(box,list.nextSibling)}
function renderExtras(){renderDay();renderIroning();renderWorkSchedule();renderDish();renderTransfer()}
function start(){addStyles();wrapTaskHTML();wrapRaw();if(state.planEngineVersion!==VERSION)replan();else{try{render()}catch(_){}renderExtras()}let oldRender=window.render;if(typeof oldRender==='function'&&!oldRender.__mcbSept){window.render=function(){let r=oldRender.apply(this,arguments);setTimeout(renderExtras,0);return r};window.render.__mcbSept=true}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();